### ISSUE TITLE
¿Deberíamos pasar la documentación aquí?

### ISSUE THREAD

**Issue by frikiman34** [frikiman34/FontanAPI#9]
Podríamos pasar la docu a markdown y mantenerla junto al código, así, cuando modificamos algo del código, también se hace con la docu. Podemos "compilarla" a HTML cuando queramos usando ShowDown [https://github.com/showdownjs/showdown]. ¿Qué te parece @ivanchi88 ?

**Comment by ivanchi88** [comment]
# Vale
## Si que es buena idea tener todo en un sitio centralizado
### Asi es más cómodo además para luego consultar 
#### Las cosas 
##### eco eco eco...

**Comment by frikiman34** [comment]
JAJAJA va, creo un nuevo ticket
